[package]
name = "mmledger"
version = "0.1.1"
license = "Apache-2.0"
homepage = "https://github.com/jarkkojs/mmledger"
repository = "https://github.com/jarkkojs/mmledger"
description = "Ledger for shims to track mm-calls"
edition = "2021"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
bitflags = "1.0.4"
heapless = "0.7.10"
libc = "0.2.71"
